default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:       index, follow

  stylesheets:    [main.css, /sf/sf_admin/css/main.css, chosen, http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css]

  javascripts:    [jquery-1.10.1.min.js,chosen.jquery.js, backend, jquery.checkboxes-1.0.5.min.js,/js/jsapi.js,/js/map/map_funcs.js,/assets/dichungdulich/js/geoaddressmap.js,/js/map/jquery.geocomplete.js]

  has_layout:     on
  layout:         layout
