generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      RowPageFooter
    theme:            default
    list:
      object_actions:
        _edit:         ~
        _delete:       ~
      actions:
        _create:       ~
      display:  [id,Partner,name]