default:
  http_metas:
    content-type: text/html
  metas:
    title:        'Đi chung xe - Hệ thống mua bán chỗ trực tuyến lớn nhất Việt Nam'
    robots:       'index,follow'
    description:  'Dichung.vn là thị trường mua bán chỗ trống trực tuyến, nơi bạn có thể tìm người đi chung về quê, ra sân bay, đi du lịch, đi học, đi làm, đi chơi.'
    keywords:     'Đi chung xe về quê, đi học, đi làm, tiết kiệm, bảo vệ môi trường, tìm người đi chung xe, tim nguoi di chung xe, di chung xe ve que, di hoc, di lam, tiem kiem, tìm người đi du lịch chung, tim nguoi di du lich, du lich gia re, du lịch giá rẻ, cách tiết kiệm xăng xe, cach tiet kiem xang xe, di chung xe ra san bay, đi chung xe ra sân bay, tìm bạn cùng đường, tim ban cung duong'
  has_layout:     off
  layout:         layout