<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/08/19 09:47:59


$this->setDatabase('propel', new sfPropelDatabase(array (
  'dsn' => 'mysql://root:@localhost/dichungdulich',
  'encoding' => 'utf8',
  'name' => 'propel',
)));

$this->setDatabase('dichung_new', new sfPropelDatabase(array (
  'dsn' => 'mysql://root:@localhost/dichung_new',
  'encoding' => 'utf8',
  'name' => 'dichung_new',
)));

$this->setDatabase('giaothong', new sfPropelDatabase(array (
  'phptype' => 'mysql',
  'host' => '123.30.187.189',
  'database' => 'giaothong',
  'username' => 'giaothong',
  'password' => 'giaothong123@',
  'encoding' => 'utf8',
  'name' => 'giaothong',
)));

$this->setDatabase('dichung_taxi', new sfPropelDatabase(array (
  'phptype' => 'mysql',
  'host' => '123.30.187.190',
  'database' => 'dichung_taxi',
  'username' => 'local',
  'password' => 332211123,
  'encoding' => 'utf8',
  'persistent' => true,
  'name' => 'dichung_taxi',
)));

$this->setDatabase('app_location', new sfPropelDatabase(array (
  'phptype' => 'mysql',
  'host' => '123.30.187.189',
  'database' => 'app_location',
  'username' => 'local',
  'password' => 332211123,
  'encoding' => 'utf8',
  'name' => 'app_location',
)));

$this->setDatabase('mail', new sfPropelDatabase(array (
  'phptype' => 'mysql',
  'host' => '123.30.187.190',
  'database' => 'mail_server',
  'username' => 'dichung',
  'password' => 'dichung123@',
  'encoding' => 'utf8',
  'name' => 'mail',
)));
