<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/08/19 09:47:59
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfTwig',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
  'mod_'.strtolower($moduleName).'_partial_view_class' => 'sfTwig',
));
