generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      ContactFooter
    theme:            default
    list:
      object_actions:
        _edit:         ~
        _delete:       ~
      actions:
        _create:       ~
      display : [id,Partner,content]
    edit:
      fields:
        content: { params: class=ckeditor size=80x60}