<?php
// auto-generated by sfPropelAdmin
// date: 2010/03/31 11:31:57
?>
<?php use_helper('I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>
<div id="right">
	<div class="header">
    	<div class="header-box">
			<ul class="tab-top">
				
						<li class="li-lt">
							<div class="right">
								<a href="#" onClick="document.getElementById('popup').style.display = 'block';" class="link"><span class="center"><strong><?php echo __('Edit password', 
array()) ?></strong></span></a>                
							</div>
						</li>
						<li class="li-rt">
							<div class="span">&nbsp;</div>
						</li>
        
				<div class="clear"></div>
                
        </ul>        
    </div>
  </div>
    <div class="content">
    	<div class="top">
			<div class="detail" align="center">
				<form action="" method="post">
					<table width="600" border="0" align="center" cellpadding="3" cellspacing="3">
					  <tr>
						<td width="130">&nbsp;</td>
						<td width="108">&nbsp;</td>
						<td width="348">&nbsp;</td>
					  </tr>
					  
					  <tr>
						<td>&nbsp;</td>
						<td>Username: </td>
						<td><label>
						  <input type="text" name="user[user_name]" style="width:180px;"  value="<?php echo $sf_user->getAttribute('username', '', 'user') ?>" readonly="" />
						</label></td>
					  </tr>
					  <tr>
						<td>&nbsp;</td>
						<td>Password:</td>
						<td><label>
						  <input type="password" name="user[password]" style="width:180px;" />
						</label></td>
					  </tr>
					  <tr>
						<td>&nbsp;</td>
						<td colspan="2"><table width="100%" border="0">
						  <tr>
							<td width="36%">&nbsp;</td>
							<td width="30%"><label>
							  <input type="submit" name="Submit" value="Submit" class="button" />
							</label></td>
							<td width="34%">&nbsp;</td>
						  </tr>
						</table></td>
						</tr>
					  <tr>
						<td colspan="3" style="color:#FF0000"><?php if ($sf_flash->has('notice')) echo $sf_flash->get('notice');?></td>
						</tr>
					</table>
					</form>
			</div>            
      </div>
			
    </div>
</div>


